baseURL = "https://encompagniedesetoiles.fr"
languageCode = "FR-fr"
title = "En Compagnie des Ã‰toiles"
theme = "PaperMod"
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true


[security.funcs]
getenv = ['^STRIPE_', '^HUGO_', '^CI$']