[build]
  publish = "public"
  command = "hugo --config hugo.toml"
  environment = { HUGO_VERSION = "0.146.0" }
	
[functions]
directory = "functions"
node_bundler = "esbuild"

[blobs]
enabled = true
